### ISSUE TITLE
KeyError: ''AUX"

### ISSUE THREAD

**Issue by aniketpanjwani** [Vuizur/add-stress-to-epub#12]
![image](https://user-images.githubusercontent.com/16311215/224489975-10f05e4f-0df3-4df3-971a-43a62ac25010.png)

I'm running your tool on Windows 11. I get a bunch of "Apparently wrong POS detected" messages, and then the tool fails with KeyError: 'AUX', all within about 30 seconds.

[Here](http://62.182.86.140/main/2447000/f4cfb3953c1023b254d9dd883d4fdd6f/%D0%AD%D0%BB%D0%B8%D0%B5%D0%B7%D0%B5%D1%80%20%D0%AE%D0%B4%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9%20-%20%D0%93%D0%B0%D1%80%D1%80%D0%B8%20%D0%9F%D0%BE%D1%82%D1%82%D0%B5%D1%80%20%D0%B8%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BC%D1%8B%D1%88%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-hpmor.ru%20%282019%29.epub) is the file on which I'm trying to add stress marks. Any feedback is appreciated!

**Comment by Vuizur** [comment]
I pushed code that should fix the issue. I couldn't reproduce the error personally, how exactly are you running the program? As a library, the exe file or did you clone the repo?

**Comment by aniketpanjwani** [comment]
I was using the exe file, and whatever you pushed fixed the issue. Thanks!
