### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by NilocEsrom** [Vuizur/add-stress-to-epub#13]
Hi there!
Cool concept and exactly what I've been looking for to add stress marks to sentences from the SMARTool database to make Anki decks.

I installed on my Linux Mint 20 machine using
`pip3 install git+https://github.com/Vuizur/add-stress-to-epub`

When I run your example in my Python script,  I get the following error at the import line:
```
File "/home/user_name/.local/lib/python3.8/site-packages/russian_text_stresser/russian_dictionary.py", line 45, in <module>
    class RussianDictionary:
  File "/home/user_name/.local/lib/python3.8/site-packages/russian_text_stresser/russian_dictionary.py", line 46, in RussianDictionary
    def __init__(self, db_file: str, simple_cases_file: str | None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by Vuizur** [comment]
It is caused by the type annotation I used (str | None).

I am currently away and will edit it only in a few weeks, but you can fix
it in two ways:

1. Upgrade to Python 3.10+
2. Delete the type annotation

Hope that helps.

Dne po 29. 5. 2023 8:17 uživatel Colin Morse ***@***.***>
napsal:

**Comment by NilocEsrom** [comment]
Thanks for the reply speed!

Do I delete part of:
`def __init__(self, db_file: str, simple_cases_file: str | None) -> None:`

**Comment by Vuizur** [comment]
Yes, so that it ends up as

def __init__(self, db_file: str, simple_cases_file) -> None:



Dne po 29. 5. 2023 9:09 uživatel Colin Morse ***@***.***>
napsal:

**Comment by NilocEsrom** [comment]
Works a treat!
Thanks so much. This is fantastic!
