### ISSUE TITLE
Offical™ embedded font

### ISSUE THREAD

**Issue by equwal** [Vuizur/add-stress-to-epub#15]
Hello,

I'm very impressed by the project and found it a few minutes ago.

I've noticed that the display of accented characters has a lot of variety depending on whatever fonts are embedded in the book or whatever. It would be nice for users to be able to add a font known to be good with calibre (maybe a wiki page)?

(edit: looks like this is a bug in KOReader, where it calls up a "fallback font" for the accented characters)

**Comment by equwal** [comment]
The workaround I found is like this:
1. Install Google Liberata font (it has multiple weights)
2. Set Liberata 7pt (heavy) as default font (press and hold to get the dialogue)
3. Set Liberata 36pt (lighter) as the fallback font

This is a mostly readable experience.

**Comment by Vuizur** [comment]
Thanks for the feedback!
I think that in KOReader the best option is to disable "Embedded Fonts". That way it uses Noto Serif for everything, and the accents get displayed fine.

I added the following guide to the Readme:

>It's best to disable "Embedded Fonts" in this case. Open the menu by clicking somewhere at the top, then in the menu at the bottom of the page select the settings wheel symbol on the rightmost side. Set here "Embedded Fonts" to "off".

**Comment by equwal** [comment]
> Thanks for the feedback! I think that in KOReader the best option is to disable "Embedded Fonts". That way it uses Noto Serif for everything, and the accents get displayed fine.
> 
> I added the following guide to the Readme:
> 
> > It's best to disable "Embedded Fonts" in this case. Open the menu by clicking somewhere at the top, then in the menu at the bottom of the page select the settings wheel symbol on the rightmost side. Set here "Embedded Fonts" to "off".

Yes, after some mucking around I figured out that disabling this feature by unchecking the box solves the issue.
