### ISSUE TITLE
This project is awesome

### ISSUE THREAD

**Issue by theAdamColton** [Vuizur/add-stress-to-epub#8]
This combined with [https://github.com/Vuizur/Wiktionary-Dictionaries](https://github.com/Vuizur/Wiktionary-Dictionaries) absolutely improved my reading experience on my kindle tenfold. Right now I am cruising through Гарри Поттер и Философский камень. Thank you

**Comment by Vuizur** [comment]
Thanks a lot for the kind words, you're welcome 👍.
